In [1]:
#Understand WHY some states perform better.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

In [2]:
master = pd.read_csv("../output/SDG_Master.csv")

master.head()

,state,year,sdg_india_index_no_poverty,sdg_india_index_zero_hunger,sdg_india_index_good_health_and_well_being,sdg_india_index_quality_education,sdg_india_index_gender_equality,sdg_india_index_clean_water_and_sanitation,sdg_india_index_affordable_and_clean_energy,sdg_india_index_decent_work_and_economic_growth,sdg_india_index_industry_innovation_and_infrastructure,sdg_india_index_reduced_inequality,sdg_india_index_sustainable_cities_and_communities,sdg_india_index_responsible_consumption_and_production,sdg_india_index_climate_action,sdg_india_index_life_on_land,sdg_india_index_peace_justice_and_strong_institutions,composite_score_of_sdg_india_index,mean_shore_zone_coastal_water_quality_biochemical_oxygen_demand_bod,mean_shore_zone_coastal_water_quality_total_nitrogen_tn,increase_in_area_under_mangroves_percent,average_marine_acidity_ph_measured_at_representative_sampling_stations_in_the_shore_zone,potential_area_available_for_developed_under_aquaculture_percent,population_living_below_the_national_poverty_line_percent,head_count_ratio_as_per_the_multidimensional_poverty_index_percent,households_with_any_usual_member_covered_by_a_health_scheme_or_health_insurance_percent,persons_provided_employment_to_the_persons_who_demanded_employment_under_mahatma_gandhi_national_rural_employment_guarantee_act_mgnrega_percent,population_out_of_total_eligible_population_receiving_social_protection_benefits_under_pradhan_mantri_matru_vandana_yojana_pmmvy_and_child_development_percent,households_living_in_katcha_houses_percent,population_in_the_lowest_two_wealth_quintiles_percent,elected_women_over_total_seats_in_the_state_or_utlok_sabha_elections_percent,seats_held_by_women_in_panchayati_raj_institutions_percent,scheduled_caste_sc_or_scheduled_tribe_st_seats_in_state_legislative_assemblies_percent,ratio_of_transgender_to_male_labour_force_participation_rate_lfpr_5th_employment,rate_of_total_crimes_against_scheduled_caste_sc_per_1_00_000_sc_population,rate_of_total_crimes_against_scheduled_tribes_st_per_1_00_000_st_population,urban_households_living_in_katcha_houses_percent,deaths_due_to_road_accidents_in_urban_areas_per_1_00_000_population,wards_with_100_percent_door_to_door_waste_collection_under_swachh_bharat_mission_urban_sbmu_percent,household_toilets_constructed_against_target_percent,municipal_solid_wast_msw_processed_to_the_total_municipal_solid_wast_msw_generated_sbmu_percent,wards_with_100_percent_source_segregation_sbm_u_percent,installed_sewage_treatment_capacity_to_sewage_generated_in_urban_areas_percent,urban_households_with_drainage_facility_percent,per_capita_fossil_fuel_consumption,use_of_nitrogenous_fertilizer_out_of_total_n_p_k_nitrogen_phosphorous_potassium_percent,hazardous_waste_generated_per_1_000_population_per1000populationperannum,quantity_of_hazardous_waste_recycled_or_utilized_to_total_hazardous_waste_generated_percent,plastic_waste_generated_per_1_000_population_implementation_of_plastic_waste_management_rules_2011_census_population_projections_per1000populationperannum,biomedical_waste_treated_to_total_quality_of_biomedical_waste_generated_percent,installed_capacity_of_grid_interactive_bio_power_per_10_lakh_population,human_lives_lost_per_1_crore_population_due_to_extreme_weather_events,disaster_preparedness_score_as_per_disaster_resilience_index,renewable_energy_out_of_total_installed_generating_capacity_including_allocated_shares_percent,co2_saved_from_light_emitting_diode_led_bulbs_per_1_000_population,disability_adjusted_life_years_daly_rate_attributable_to_air_pollution_per_1_00_000_population,forest_covered_to_the_total_geographical_area_percent,tree_covered_to_the_geographical_area_percent,geographical_area_covered_by_forest_and_trees_percent,area_covered_under_afforestation_schemes_to_the_total_geographical_area_percent,degraded_land_over_total_land_area_percent,increase_in_area_of_desertification_percent,cases_under_wildlife_protection_act_1972_per_million_hectares_of_protected_area,murders_per_1_00_000_population,cognizable_crimes_against_children_per_1_00_000_population,victims_of_human_trafficking_per_10_lakh_population,missing_children_per_1_00_000_child_population,courts_per_1_00_000_population,cases_under_prevention_of_corruption_act_and_related_sections_of_ipc_per_10_lakh_population,births_registered_percent,population_covered_under_aadhaar_percent,beneficiaries_covered_under_national_food_security_act_nfsa_2013_percent,children_who_are_underweight_under_five_years_of_age_percent,children_who_are_stunned_under_five_years_of_age_percent,anaemic_pregnant_women_in_the_age_group_of_15_to_49_years_percent,anaemic_adolescents_in_the_age_group_of_10_to_19_years_percent,rice_and_wheat_produced_annually_per_unit_area_directorate_of_economics_and_statistics_2018_19,gross_value_added_constant_prices_in_agriculture_per_worker,maternal_mortality_ratio_per_1_00_000_live_births,mortality_rate_per_1_000_live_births_under_5_years_of_age,fully_immunized_children_in_the_age_group_of_9_to_11_months_percent,notification_rate_of_tuberculosis_cases_per_1_00_000_population,human_immunodeficiency_virus_hiv_incidence_per_1_000_uninfected_population,suicide_rate_per_1_00_000_population,death_rate_due_to_road_traffic_accidents_per_1_00_000_population,institutional_deliveries_out_of_the_total_deliveries_reported_percent,monthly_per_capita_out_of_pocket_expenditure_on_health_as_a_share_of_monthly_per_capita_consumption_expenditure_mpce,number_of_physicians_nurses_and_midwives_per_10_000_population,adjusted_net_enrolment_ratio_aner_in_elementary_education_for_classes_1_to_8,average_annual_dropout_rate_at_secondary_level_for_classes_9_to_10,gross_enrolment_ratio_ger_in_higher_secondary_for_classes_11_to_12,students_in_grade_viii_achieving_atleast_a_minimum_proficiency_level_in_terms_of_nationally_defined_learning_outcomes_to_be_attained_by_the_pupils_at_the_end_of_the_grade_percent,gross_enrolment_ratio_ger_in_higher_education_in_the_age_group_of_18_to_23_years,persons_with_disability_completed_at_least_secondary_education_with_age_15_years_and_above_percent,gender_parity_index_gpi_for_higher_education_in_the_age_group_18_to_23_years,literate_persons_under_the_age_of_15_years_and_above_percent,schools_with_access_to_basic_infrastructure_such_as_electricity_drinking_water_percent,trained_teachers_at_secondary_level_for_classes_9_to_10_percent,pupil_teacher_ratio_ptr_at_secondary_level_for_classes_9_to_10,rate_of_crimes_against_women_per_1_00_000_female_population,sex_ratio_at_birth,ratio_of_female_to_male_average_wage_received_among_regular_wage_or_salaried_employees,per_lakh_women_who_have_experienced_cruelty_or_physical_violence_by_husband_or_his_relatives_during_the_year,elected_women_over_total_seats_in_the_state_legislative_assembly_percent,ratio_of_female_to_male_labour_force_participation_rate_lfpr_in_the_age_group_of_15_to_59_years,proportion_of_women_in_managerial_positions_including_women_in_board_of_directors_in_listed_companies_per_1_000_persons,currently_married_women_with_satisfied_family_planning_methods_percent,operational_land_holding_gender_wise_percentage_of_female_operated_operational_holdings_percent,rural_population_getting_safe_and_adequate_drinking_water_within_premises_through_pipe_water_supply_pws_percent,rural_population_having_improved_source_of_drinking_water_percent,individual_household_toilets_constructed_against_target_under_swachh_bharat_mission_gramin_percent,districts_verified_to_be_open_defication_free_odf_status_under_swachh_bharat_mission_gramin_percent,schools_with_separate_toilet_facility_for_girls_percent,industries_complying_with_wastewater_treatment_17_categories_of_highly_polluting_industries_or_grossly_polluting_or_red_category_of_industries_complying_with_wastewater_treatment_percent,ground_water_withdrawal_against_availability_percent,blocks_mandals_taluka_over_exploited_percent,households_electrified_under_ministry_of_power_in_2019_percent,lpg_png_connections_against_number_of_households_as_per_mopng_calculations_as_on_31072020_percent,annual_growth_rate_of_per_capita_gross_domestic_product_gdp_at_constant_prices,ease_of_doing_business_eodb_feedback_score,unemployment_rate_in_the_age_group_of_15_to_59_years_percent,labour_force_participation_rate_lfpr_percent_in_the_age_group_of_15_to_59_years,regular_wage_or_salaried_employees_in_non_agriculture_sector_without_any_social_security_benefit_percent,households_covered_with_a_bank_account_under_pmjdy_against_target_percent,functioning_branches_of_commercial_banks_per_1_00_000_population,automated_teller_machines_atms_per_1_00_000_population,women_account_holders_under_pradhan_mantri_jan_dhan_yojana_pmjdy_percent,targeted_habitations_connected_by_all_weather_roads_under_pradhan_mantri_gram_sadak_yojana_pmgsy,share_of_gross_value_added_gva_in_manufacturing_to_total_gross_value_added_gva_in_current_prices_percent,manufacturing_employment_as_a_percentage_of_total_employment_percent,innovation_score_as_per_the_india_innovation_index,score_as_per_logistics_ease_across_different_states_leads_report,mobile_connections_per_100_persons_mobile_tele_density_as_per_deptof_telecommunications,internet_subscribers_per_100_population_as_per_deptof_telecommunications
0,Andaman And Nicobar Islands,"Calendar Year (Jan - Dec), 2020",71,45,68,57,68,87,100,59,23,67,85,73,77,72,46,67,NaN,NaN,NaN,NaN,NaN,1.00,6.9,5.7,82.961898,96.73,0.0,16.0,0.00,35.66,NaN,NaN,NaN,10.5,0.0,4.166667,100.000000,100.0,95.555556,100.000000,0.000000,88.4,558.0,46.987952,0.000404,0.000000,4.671717,100.000000,NaN,NaN,20.5,46.256039,104.930175,NaN,81.74,0.50,82.24,0.086435,6.416293,NaN,13.0,3.3,112.5,0.000000,30.714286,0.000000,7.500000,71.8,98.0,100.00,NaN,NaN,61.4,NaN,2122.08,NaN,NaN,NaN,66.0,151,0.05,45.5,5.025126,98.2,7.0,NaN,74.10,22.22,56.44,65.50,23.2,28.5,1.29,88.3,96.014493,85.054773,10.0,72.2,NaN,0.95,0.526316,NaN,0.39,NaN,73.0,29.797557,88.888889,100.000000,100,100,99.28,60.000000,3.030303,0.000000,NaN,115.151515,NaN,4.64,13.8,62.5,59.3,100.00,18.796992,29.824561,47.94,0.000000,1.089261,7.19,18.89,NaN,87.87,NaN
1,Andhra Pradesh,"Calendar Year (Jan - Dec), 2020",81,52,77,50,58,92,100,67,52,74,78,84,63,69,77,72,0.79,40.5,0.0,8.07,37.104023,9.20,15.6,74.6,83.808651,96.40,3.2,22.4,16.00,50.00,20.571429,0.99,24.5,12.5,0.7,16.113744,100.000000,126.0,63.670412,96.802581,18.640089,89.7,158.4,59.575931,11.279270,75.992319,1.274485,100.000000,9.635735,15.567343,19.5,40.725277,43.867585,3007.0,17.88,2.40,20.28,1.407694,33.814958,1.368330,5.0,1.7,16.1,7.626147,17.523931,1.211774,2.350917,90.2,100.0,100.00,35.5,31.5,52.9,21.7,3729.47,0.731587,65.0,33.0,87.0,189,0.05,12.4,15.261397,99.6,13.5,95.143868,87.98,16.37,46.84,80.15,32.4,15.4,0.81,65.6,91.259961,75.176596,16.0,67.9,920.0,0.71,30.420811,8.000000,0.55,208.0,93.6,30.086439,68.518324,99.811252,100,100,97.28,96.816976,44.168734,6.716418,100.0,101.157524,3.838030,52.40,5.7,63.5,62.5,100.00,14.397612,21.008004,59.31,98.460292,9.580831,10.60,24.19,3.42,85.71,65.61
2,Arunachal Pradesh,"Calendar Year (Jan - Dec), 2020",54,66,64,41,37,67,85,50,31,69,39,77,58,93,64,60,NaN,NaN,NaN,NaN,NaN,34.67,24.4,58.3,95.435862,92.76,29.0,43.6,0.00,38.99,98.333333,1.39,NaN,0.0,8.9,11.764706,82.432432,80.0,23.974763,48.648649,0.000000,59.4,179.7,0.000000,NaN,NaN,2.536752,100.000000,0.000000,221.031480,11.5,84.782451,34.185426,1436.0,79.63,1.01,80.64,NaN,11.736635,12.617971,4.0,4.0,32.7,2.649007,9.361702,2.715232,8.609272,100.0,83.0,100.00,16.0,28.0,33.8,26.4,1806.62,1.286107,NaN,NaN,68.0,182,0.05,7.4,7.232913,89.6,17.0,21.623816,80.98,35.98,38.48,59.95,29.7,10.3,0.99,79.9,50.935935,79.036496,14.0,43.3,NaN,0.56,7.397260,5.000000,0.26,NaN,50.0,12.072969,34.125099,92.636580,100,100,70.12,70.893372,0.374532,0.000000,100.0,84.049080,2.516181,0.00,7.7,44.8,17.3,100.00,11.826544,16.360053,55.05,81.747270,3.200942,2.05,14.90,2.77,84.00,52.34
3,Assam,"Calendar Year (Jan - Dec), 2020",51,41,59,43,25,64,98,50,39,65,55,66,53,78,62,57,NaN,NaN,NaN,NaN,NaN,31.98,36.2,10.4,86.109387,95.32,2.4,62.5,7.14,54.60,19.047619,0.60,0.9,0.1,0.4,24.702038,87.910923,97.0,63.244730,42.735949,0.107635,58.7,88.0,66.643685,1.337720,20.915679,0.948150,75.048046,0.057483,15.568546,23.0,32.272020,21.472451,3464.0,36.11,1.80,37.91,NaN,9.452268,25.231950,63.0,3.6,55.6,7.205113,11.858705,1.350959,0.522952,100.0,45.0,94.27,29.4,32.4,44.8,36.9,2147.44,0.620668,215.0,47.0,85.0,141,0.04,6.9,9.428206,91.1,12.9,22.571581,96.36,31.47,30.94,79.55,18.7,16.8,0.95,84.9,59.513901,29.294607,11.0,177.8,925.0,0.53,70.728242,6.349206,0.17,221.0,55.6,1.668046,25.699994,74.724722,100,100,75.30,90.017212,11.253092,0.000000,100.0,97.605843,5.255325,5.93,7.1,49.4,44.8,99.96,8.892593,11.600034,59.26,94.376955,12.252417,10.55,16.38,3.00,67.51,41.57
4,Bihar,"Calendar Year (Jan - Dec), 2020",32,31,66,29,48,91,78,50,24,48,67,59,16,62,73,52,NaN,NaN,NaN,NaN,NaN,33.74,52.5,12.3,78.599921,87.97,8.2,75.2,7.50,52.02,16.460905,0.59,39.5,7.3,1.1,21.629506,99.437370,103.0,58.274648,52.798342,5.620609,87.8,50.5,68.584991,0.138161,28.405407,0.582283,28.834587,1.023012,NaN,19.5,7.913385,16.646372,4308.0,7.76,2.13,9.89,0.372907,12.655480,5.347675,9.0,2.6,20.8,2.630922,16.299687,1.581883,0.591125,80.3,86.0,99.85,38.7,42.0,58.3,28.1,2374.02,0.285550,149.0,37.0,94.0,100,0.07,0.5,5.998468,84.8,14.5,16.788101,86.54,28.46,26.39,78.30,13.6,18.5,0.79,64.7,88.664016,78.442195,58.0,32.3,895.0,0.75,4.583478,11.522634,0.06,214.0,51.4,13.996113,65.187443,96.286309,100,100,97.92,96.844181,45.739910,2.247191,100.0,76.554045,7.628639,2.78,10.6,41.4,23.7,100.00,6.372698,6.841954,56.22,97.182163,7.213315,5.30,14.48,2.85,50.65,30.99

In [3]:
print(master.shape)

(36, 134)

In [4]:
top10 = master.nlargest(
    10,
    "composite_score_of_sdg_india_index"
)

bottom10 = master.nsmallest(
    10,
    "composite_score_of_sdg_india_index"
)

In [5]:
top10[["state","composite_score_of_sdg_india_index"]]

               state  composite_score_of_sdg_india_index
5         Chandigarh                                  79
15            Kerala                                  75
11  Himachal Pradesh                                  74
29        Tamil Nadu                                  74
1     Andhra Pradesh                                  72
8                Goa                                  72
14         Karnataka                                  72
34       Uttarakhand                                  72
28            Sikkim                                  71
19       Maharashtra                                  70

In [6]:
bottom10[["state","composite_score_of_sdg_india_index"]]

                state  composite_score_of_sdg_india_index
4               Bihar                                  52
13          Jharkhand                                  56
3               Assam                                  57
2   Arunachal Pradesh                                  60
21          Meghalaya                                  60
27          Rajasthan                                  60
33      Uttar Pradesh                                  60
6        Chhattisgarh                                  61
23           Nagaland                                  61
24             Odisha                                  61

In [7]:
# Compare High vs Low Performers

comparison = pd.DataFrame({
    "Top10": top10.mean(numeric_only=True),
    "Bottom10": bottom10.mean(numeric_only=True)
})

comparison["Difference"] = (
    comparison["Top10"] -
    comparison["Bottom10"]
)

comparison.head()

                                            Top10  Bottom10  Difference
sdg_india_index_no_poverty                   77.6      52.0        25.6
sdg_india_index_zero_hunger                  65.2      43.1        22.1
sdg_india_index_good_health_and_well_being   75.4      65.1        10.3
sdg_india_index_quality_education            67.9      45.6        22.3
sdg_india_index_gender_equality              56.7      45.9        10.8

In [10]:
comparison.shape

(132, 3)

In [8]:
comparison.sort_values(
    by="Difference",
    ascending=False
).head(20)

,Top10,Bottom10,Difference
rice_and_wheat_produced_annually_per_unit_area_directorate_of_economics_and_statistics_2018_19,2893.084000,2209.369000,683.715000
per_capita_fossil_fuel_consumption,251.600000,122.510000,129.090000
human_lives_lost_per_1_crore_population_due_to_extreme_weather_events,95.441910,44.140680,51.301229
notification_rate_of_tuberculosis_cases_per_1_00_000_population,216.300000,165.700000,50.600000
mobile_connections_per_100_persons_mobile_tele_density_as_per_deptof_telecommunications,118.454000,69.680000,48.774000
installed_sewage_treatment_capacity_to_sewage_generated_in_urban_areas_percent,57.245131,12.558819,44.686312
lpg_png_connections_against_number_of_households_as_per_mopng_calculations_as_on_31072020_percent,116.021580,82.120035,33.901546
number_of_physicians_nurses_and_midwives_per_10_000_population,52.910342,20.753395,32.156947
schools_with_access_to_basic_infrastructure_such_as_electricity_drinking_water_percent,95.755253,69.897909,25.857344
sdg_india_index_no_poverty,77.600000,52.000000,25.600000
rural_population_getting_safe_and_adequate_drinking_water_within_premises_through_pipe_water_supply_pws_percent,63.019316,38.363518,24.655798
gross_enrolment_ratio_ger_in_higher_secondary_for_classes_11_to_12,67.434000,43.083000,24.351000
sdg_india_index_industry_innovation_and_infrastructure,59.500000,35.500000,24.000000
population_covered_under_aadhaar_percent,101.600000,78.900000,22.700000
internet_subscribers_per_100_population_as_per_deptof_telecommunications,66.738889,44.220000,22.518889
sdg_india_index_quality_education,67.900000,45.600000,22.300000
sdg_india_index_zero_hunger,65.200000,43.100000,22.100000
automated_teller_machines_atms_per_1_00_000_population,33.770640,12.317544,21.453096
wards_with_100_percent_source_segregation_sbm_u_percent,88.266936,67.880277,20.386659
trained_teachers_at_secondary_level_for_classes_9_to_10_percent,85.741921,66.648055,19.093866

In [9]:
comparison.sort_values(
    by="Difference",
    ascending=True
).head(20)

,Top10,Bottom10,Difference
disability_adjusted_life_years_daly_rate_attributable_to_air_pollution_per_1_00_000_population,2391.555556,3131.700000,-740.144444
maternal_mortality_ratio_per_1_00_000_live_births,67.500000,157.857143,-90.357143
population_in_the_lowest_two_wealth_quintiles_percent,15.080000,55.770000,-40.690000
mean_shore_zone_coastal_water_quality_total_nitrogen_tn,29.705000,65.000000,-35.295000
scheduled_caste_sc_or_scheduled_tribe_st_seats_in_state_legislative_assemblies_percent,21.152046,50.268243,-29.116197
potential_area_available_for_developed_under_aquaculture_percent,13.718270,41.731013,-28.012742
head_count_ratio_as_per_the_multidimensional_poverty_index_percent,9.920000,36.160000,-26.240000
mortality_rate_per_1_000_live_births_under_5_years_of_age,23.714286,42.000000,-18.285714
population_living_below_the_national_poverty_line_percent,12.020000,28.476000,-16.456000
rate_of_crimes_against_women_per_1_00_000_female_population,52.180000,66.270000,-14.090000
anaemic_adolescents_in_the_age_group_of_10_to_19_years_percent,18.222222,28.390000,-10.167778
pupil_teacher_ratio_ptr_at_secondary_level_for_classes_9_to_10,14.700000,24.300000,-9.600000
rate_of_total_crimes_against_scheduled_caste_sc_per_1_00_000_sc_population,13.290000,22.187500,-8.897500
average_annual_dropout_rate_at_secondary_level_for_classes_9_to_10,13.160000,21.773000,-8.613000
children_who_are_stunned_under_five_years_of_age_percent,26.444444,34.530000,-8.085556
children_who_are_underweight_under_five_years_of_age_percent,23.688889,31.080000,-7.391111
degraded_land_over_total_land_area_percent,18.699734,25.470031,-6.770297
anaemic_pregnant_women_in_the_age_group_of_15_to_49_years_percent,39.900000,46.460000,-6.560000
households_living_in_katcha_houses_percent,1.290000,7.470000,-6.180000
forest_covered_to_the_total_geographical_area_percent,32.919000,39.005000,-6.086000

In [ ]:
# Markdown
# Education indicators show strong association with SDG performance.
# Poverty remains the largest barrier to sustainable development.
# Better internet and mobile connectivity are associated with higher SDG scores.
# Maternal and child health outcomes significantly influence development performance.
# Industry & Innovation is India's weakest-performing SDG.
# Affordable & Clean Energy is India's strongest-performing SDG.