In [1]:
# A Random Forest model trained on 100+ SDG indicators identified the top predictors of SDG performance.
# so we will predict composite_score_of_sdg_india_index using all indicators as features

In [2]:
import pandas as pd
import sklearn

In [3]:
master = pd.read_csv("../output/SDG_Master.csv")

In [4]:
master.shape

(36, 134)

In [5]:
y = master["composite_score_of_sdg_india_index"]

In [6]:
X = master.drop(
    columns=[
        "state",
        "year",
        "composite_score_of_sdg_india_index"
    ]
)

In [7]:
X.head()

,sdg_india_index_no_poverty,sdg_india_index_zero_hunger,sdg_india_index_good_health_and_well_being,sdg_india_index_quality_education,sdg_india_index_gender_equality,sdg_india_index_clean_water_and_sanitation,sdg_india_index_affordable_and_clean_energy,sdg_india_index_decent_work_and_economic_growth,sdg_india_index_industry_innovation_and_infrastructure,sdg_india_index_reduced_inequality,...,functioning_branches_of_commercial_banks_per_1_00_000_population,automated_teller_machines_atms_per_1_00_000_population,women_account_holders_under_pradhan_mantri_jan_dhan_yojana_pmjdy_percent,targeted_habitations_connected_by_all_weather_roads_under_pradhan_mantri_gram_sadak_yojana_pmgsy,share_of_gross_value_added_gva_in_manufacturing_to_total_gross_value_added_gva_in_current_prices_percent,manufacturing_employment_as_a_percentage_of_total_employment_percent,innovation_score_as_per_the_india_innovation_index,score_as_per_logistics_ease_across_different_states_leads_report,mobile_connections_per_100_persons_mobile_tele_density_as_per_deptof_telecommunications,internet_subscribers_per_100_population_as_per_deptof_telecommunications
0,71,45,68,57,68,87,100,59,23,67,...,18.796992,29.824561,47.94,0.000000,1.089261,7.19,18.89,NaN,87.87,NaN
1,81,52,77,50,58,92,100,67,52,74,...,14.397612,21.008004,59.31,98.460292,9.580831,10.60,24.19,3.42,85.71,65.61
2,54,66,64,41,37,67,85,50,31,69,...,11.826544,16.360053,55.05,81.747270,3.200942,2.05,14.90,2.77,84.00,52.34
3,51,41,59,43,25,64,98,50,39,65,...,8.892593,11.600034,59.26,94.376955,12.252417,10.55,16.38,3.00,67.51,41.57
4,32,31,66,29,48,91,78,50,24,48,...,6.372698,6.841954,56.22,97.182163,7.213315,5.30,14.48,2.85,50.65,30.99

In [8]:
X.isnull().sum().sum()

np.int64(338)

In [9]:
missing = X.isnull().sum()

missing[missing > 0].sort_values(ascending=False)

mean_shore_zone_coastal_water_quality_total_nitrogen_tn                                                                                                                                       28
mean_shore_zone_coastal_water_quality_biochemical_oxygen_demand_bod                                                                                                                           27
increase_in_area_under_mangroves_percent                                                                                                                                                      27
average_marine_acidity_ph_measured_at_representative_sampling_stations_in_the_shore_zone                                                                                                      27
potential_area_available_for_developed_under_aquaculture_percent                                                                                                                              27
maternal_mortality_ratio_per_1_00_000_live_births                                                                                                                                             17
mortality_rate_per_1_000_live_births_under_5_years_of_age                                                                                                                                     13
sex_ratio_at_birth                                                                                                                                                                            13
installed_capacity_of_grid_interactive_bio_power_per_10_lakh_population                                                                                                                       12
human_lives_lost_per_1_crore_population_due_to_extreme_weather_events                                                                                                                         11
cases_under_wildlife_protection_act_1972_per_million_hectares_of_protected_area                                                                                                               11
ratio_of_transgender_to_male_labour_force_participation_rate_lfpr_5th_employment                                                                                                               8
proportion_of_women_in_managerial_positions_including_women_in_board_of_directors_in_listed_companies_per_1_000_persons                                                                        7
increase_in_area_of_desertification_percent                                                                                                                                                    5
rate_of_total_crimes_against_scheduled_tribes_st_per_1_00_000_st_population                                                                                                                    5
children_who_are_underweight_under_five_years_of_age_percent                                                                                                                                   5
anaemic_adolescents_in_the_age_group_of_10_to_19_years_percent                                                                                                                                 5
internet_subscribers_per_100_population_as_per_deptof_telecommunications                                                                                                                       5
children_who_are_stunned_under_five_years_of_age_percent                                                                                                                                       5
area_covered_under_afforestation_schemes_to_the_total_geographical_area_percent                                                                                                                5
targeted_habitations_connected_by_all_weather_roads_under_pradhan_mantri_gram_sadak_yojana_pmgsy                                                                                               5
disability_adjusted_life_years_daly_rate_attributable_to_air_pollution_per_1_00_000_population                                                                                                 5
households_electrified_under_ministry_of_power_in_2019_percent                                                                                                                                 4
rural_population_having_improved_source_of_drinking_water_percent                                                                                                                              4
rate_of_total_crimes_against_scheduled_caste_sc_per_1_00_000_sc_population                                                                                                                     4
scheduled_caste_sc_or_scheduled_tribe_st_seats_in_state_legislative_assemblies_percent                                                                                                         4
seats_held_by_women_in_panchayati_raj_institutions_percent                                                                                                                                     4
elected_women_over_total_seats_in_the_state_legislative_assembly_percent                                                                                                                       4
number_of_physicians_nurses_and_midwives_per_10_000_population                                                                                                                                 4
rural_population_getting_safe_and_adequate_drinking_water_within_premises_through_pipe_water_supply_pws_percent                                                                                4
gross_value_added_constant_prices_in_agriculture_per_worker                                                                                                                                    4
persons_provided_employment_to_the_persons_who_demanded_employment_under_mahatma_gandhi_national_rural_employment_guarantee_act_mgnrega_percent                                                3
quantity_of_hazardous_waste_recycled_or_utilized_to_total_hazardous_waste_generated_percent                                                                                                    3
annual_growth_rate_of_per_capita_gross_domestic_product_gdp_at_constant_prices                                                                                                                 3
hazardous_waste_generated_per_1_000_population_per1000populationperannum                                                                                                                       3
score_as_per_logistics_ease_across_different_states_leads_report                                                                                                                               2
share_of_gross_value_added_gva_in_manufacturing_to_total_gross_value_added_gva_in_current_prices_percent                                                                                       2
population_out_of_total_eligible_population_receiving_social_protection_benefits_under_pradhan_mantri_matru_vandana_yojana_pmmvy_and_child_development_percent                                 2
population_living_below_the_national_poverty_line_percent                                                                                                                                      1
household_toilets_constructed_against_target_percent                                                                                                                                           1
wards_with_100_percent_door_to_door_waste_collection_under_swachh_bharat_mission_urban_sbmu_percent                                                                                            1
wards_with_100_percent_source_segregation_sbm_u_percent                                                                                                                                        1
municipal_solid_wast_msw_processed_to_the_total_municipal_solid_wast_msw_generated_sbmu_percent                                                                                                1
tree_covered_to_the_geographical_area_percent                                                                                                                                                  1
anaemic_pregnant_women_in_the_age_group_of_15_to_49_years_percent                                                                                                                              1
rice_and_wheat_produced_annually_per_unit_area_directorate_of_economics_and_statistics_2018_19                                                                                                 1
monthly_per_capita_out_of_pocket_expenditure_on_health_as_a_share_of_monthly_per_capita_consumption_expenditure_mpce                                                                           1
human_immunodeficiency_virus_hiv_incidence_per_1_000_uninfected_population                                                                                                                     1
industries_complying_with_wastewater_treatment_17_categories_of_highly_polluting_industries_or_grossly_polluting_or_red_category_of_industries_complying_with_wastewater_treatment_percent     1
dtype: int64

In [10]:
X_clean = X.copy()

In [11]:
drop_cols = [
    "mean_shore_zone_coastal_water_quality_total_nitrogen_tn",
    "mean_shore_zone_coastal_water_quality_biochemical_oxygen_demand_bod",
    "increase_in_area_under_mangroves_percent",
    "average_marine_acidity_ph_measured_at_representative_sampling_stations_in_the_shore_zone",
    "potential_area_available_for_developed_under_aquaculture_percent"
]

X_clean = X_clean.drop(columns=drop_cols)

In [12]:
X_clean.shape

(36, 126)

In [13]:
X_clean = X_clean.fillna(
    X_clean.median(numeric_only=True)
)

In [14]:
X_clean.isnull().sum().sum()

np.int64(0)

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_clean,
    y,
    test_size=0.2,
    random_state=42
)

In [16]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, random_state=42)

In [17]:
y_pred = rf.predict(X_test)

In [18]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

mae = mean_absolute_error(y_test, y_pred)

rmse = mean_squared_error(
    y_test,
    y_pred
) ** 0.5

r2 = r2_score(y_test, y_pred)

print("MAE :", round(mae,2))
print("RMSE:", round(rmse,2))
print("R2  :", round(r2,2))

MAE : 2.73
RMSE: 3.08
R2  : 0.44

In [19]:
importance_df = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": rf.feature_importances_
})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
)

importance_df.head(20) # we get importance

                                               Feature  Importance
21   population_in_the_lowest_two_wealth_quintiles_...    0.284544
16   head_count_ratio_as_per_the_multidimensional_p...    0.123532
117  automated_teller_machines_atms_per_1_00_000_po...    0.081694
124  mobile_connections_per_100_persons_mobile_tele...    0.057001
0                           sdg_india_index_no_poverty    0.032244
116  functioning_branches_of_commercial_banks_per_1...    0.032094
88   schools_with_access_to_basic_infrastructure_su...    0.031391
82   gross_enrolment_ratio_ger_in_higher_secondary_...    0.029491
105  industries_complying_with_wastewater_treatment...    0.023982
70   maternal_mortality_ratio_per_1_00_000_live_births    0.019032
2           sdg_india_index_good_health_and_well_being    0.018901
15   population_living_below_the_national_poverty_l...    0.016129
7      sdg_india_index_decent_work_and_economic_growth    0.013843
67   anaemic_adolescents_in_the_age_group_of_10_to_...    0.009770
3                    sdg_india_index_quality_education    0.009342
29   deaths_due_to_road_accidents_in_urban_areas_pe...    0.009258
71   mortality_rate_per_1_000_live_births_under_5_y...    0.008151
74   human_immunodeficiency_virus_hiv_incidence_per...    0.008016
6          sdg_india_index_affordable_and_clean_energy    0.007224
36                  per_capita_fossil_fuel_consumption    0.007148

In [20]:
sdg_cols = [col for col in master.columns
            if col.startswith("sdg_india_index")] # drop cols of sdg_india_index of composite score

X2 = master.drop(
    columns=sdg_cols +
    ["state",
     "year",
     "composite_score_of_sdg_india_index"]
)

In [21]:
drop_cols = [
    "mean_shore_zone_coastal_water_quality_total_nitrogen_tn",
    "mean_shore_zone_coastal_water_quality_biochemical_oxygen_demand_bod",
    "increase_in_area_under_mangroves_percent",
    "average_marine_acidity_ph_measured_at_representative_sampling_stations_in_the_shore_zone",
    "potential_area_available_for_developed_under_aquaculture_percent"
]

X2 = X2.drop(columns=drop_cols)

In [22]:
X2 = X2.fillna(
    X2.median(numeric_only=True)
)

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X2,
    y,
    test_size=0.2,
    random_state=42
)

In [24]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, random_state=42)

In [25]:
y_pred = rf.predict(X_test)

In [26]:
mae = mean_absolute_error(y_test, y_pred)
rmse = mean_squared_error(
    y_test,
    y_pred
) ** 0.5
r2 = r2_score(y_test, y_pred)
print("MAE :", round(mae,2))
print("RMSE:", round(rmse,2))
print("R2  :", round(r2,2))

MAE : 2.74
RMSE: 3.07
R2  : 0.45

In [27]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    rf,
    X_clean,
    y,
    cv=5,
    scoring="r2"
)

print(scores)
print("Mean R2:", scores.mean())

[0.63131453 0.765118   0.69404381 0.94749686 0.69084503]
Mean R2: 0.7457636456913389

In [28]:
importance_df = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": rf.feature_importances_
})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
)

importance_df.head(20) # we get importance

                                               Feature  Importance
6    population_in_the_lowest_two_wealth_quintiles_...    0.243509
1    head_count_ratio_as_per_the_multidimensional_p...    0.150483
102  automated_teller_machines_atms_per_1_00_000_po...    0.106231
109  mobile_connections_per_100_persons_mobile_tele...    0.096541
101  functioning_branches_of_commercial_banks_per_1...    0.047309
73   schools_with_access_to_basic_infrastructure_su...    0.027199
67   gross_enrolment_ratio_ger_in_higher_secondary_...    0.027069
90   industries_complying_with_wastewater_treatment...    0.026810
0    population_living_below_the_national_poverty_l...    0.018913
55   maternal_mortality_ratio_per_1_00_000_live_births    0.011788
81   ratio_of_female_to_male_labour_force_participa...    0.011307
59   human_immunodeficiency_virus_hiv_incidence_per...    0.010124
52   anaemic_adolescents_in_the_age_group_of_10_to_...    0.010038
66   average_annual_dropout_rate_at_secondary_level...    0.009945
68   students_in_grade_viii_achieving_atleast_a_min...    0.009392
21                  per_capita_fossil_fuel_consumption    0.008930
69   gross_enrolment_ratio_ger_in_higher_education_...    0.008787
56   mortality_rate_per_1_000_live_births_under_5_y...    0.008347
14   deaths_due_to_road_accidents_in_urban_areas_pe...    0.008224
70   persons_with_disability_completed_at_least_sec...    0.008091

In [29]:
for feature in importance_df["Feature"].head(25):
    print(feature)

population_in_the_lowest_two_wealth_quintiles_percent
head_count_ratio_as_per_the_multidimensional_poverty_index_percent
automated_teller_machines_atms_per_1_00_000_population
mobile_connections_per_100_persons_mobile_tele_density_as_per_deptof_telecommunications
functioning_branches_of_commercial_banks_per_1_00_000_population
schools_with_access_to_basic_infrastructure_such_as_electricity_drinking_water_percent
gross_enrolment_ratio_ger_in_higher_secondary_for_classes_11_to_12
industries_complying_with_wastewater_treatment_17_categories_of_highly_polluting_industries_or_grossly_polluting_or_red_category_of_industries_complying_with_wastewater_treatment_percent
population_living_below_the_national_poverty_line_percent
maternal_mortality_ratio_per_1_00_000_live_births
ratio_of_female_to_male_labour_force_participation_rate_lfpr_in_the_age_group_of_15_to_59_years
human_immunodeficiency_virus_hiv_incidence_per_1_000_uninfected_population
anaemic_adolescents_in_the_age_group_of_10_to_19_years_percent
average_annual_dropout_rate_at_secondary_level_for_classes_9_to_10
students_in_grade_viii_achieving_atleast_a_minimum_proficiency_level_in_terms_of_nationally_defined_learning_outcomes_to_be_attained_by_the_pupils_at_the_end_of_the_grade_percent
per_capita_fossil_fuel_consumption
gross_enrolment_ratio_ger_in_higher_education_in_the_age_group_of_18_to_23_years
mortality_rate_per_1_000_live_births_under_5_years_of_age
deaths_due_to_road_accidents_in_urban_areas_per_1_00_000_population
persons_with_disability_completed_at_least_secondary_education_with_age_15_years_and_above_percent
labour_force_participation_rate_lfpr_percent_in_the_age_group_of_15_to_59_years
operational_land_holding_gender_wise_percentage_of_female_operated_operational_holdings_percent
death_rate_due_to_road_traffic_accidents_per_1_00_000_population
gross_value_added_constant_prices_in_agriculture_per_worker
lpg_png_connections_against_number_of_households_as_per_mopng_calculations_as_on_31072020_percent